IF
  RandomNum(3,1)
  Global("RandomSet10281582_2","AR7000",0)
  Global("RandomBeenSet10281582","AR7000",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet10281582_2","AR7000",1)
    SetGlobal("RandomBeenSet10281582","AR7000",1)
END

IF
  RandomNum(3,2)
  Global("RandomSet10281582_1","AR7000",0)
  Global("RandomBeenSet10281582","AR7000",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet10281582_1","AR7000",1)
    SetGlobal("RandomBeenSet10281582","AR7000",1)
END

IF
  RandomNum(3,3)
  Global("RandomSet10281582_0","AR7000",0)
  Global("RandomBeenSet10281582","AR7000",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet10281582_0","AR7000",1)
    SetGlobal("RandomBeenSet10281582","AR7000",1)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(19)
  LevelPartyLT(21)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(20)
  LevelPartyLT(22)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(21)
  LevelPartyLT(23)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(22)
  LevelPartyLT(24)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(23)
  LevelPartyLT(25)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(24)
  LevelPartyLT(26)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(25)
  LevelPartyLT(27)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(26)
  LevelPartyLT(28)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(27)
  LevelPartyLT(29)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(28)
  LevelPartyLT(30)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(29)
  LevelPartyLT(31)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(30)
  LevelPartyLT(32)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(31)
  LevelPartyLT(33)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(32)
  LevelPartyLT(34)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(33)
  LevelPartyLT(35)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(34)
  LevelPartyLT(36)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(35)
  LevelPartyLT(37)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(36)
  LevelPartyLT(38)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(37)
  LevelPartyLT(39)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(38)
  LevelPartyLT(40)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(39)
  LevelPartyLT(41)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(40)
  LevelPartyLT(42)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(41)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(19)
  LevelPartyLT(21)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(20)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(13)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(10)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(8)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(6)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_2","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    CreateCreature("SPIDHU",[1028.1582],0)  // ~Huge Spider~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(11)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(5)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(3)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(2)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(2)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(1)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_1","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(19)
  LevelPartyLT(21)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(20)
  LevelPartyLT(22)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(21)
  LevelPartyLT(23)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(22)
  LevelPartyLT(24)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(23)
  LevelPartyLT(25)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(24)
  LevelPartyLT(26)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(25)
  LevelPartyLT(27)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(26)
  LevelPartyLT(28)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(27)
  LevelPartyLT(29)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(28)
  LevelPartyLT(30)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(29)
  LevelPartyLT(31)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(30)
  LevelPartyLT(32)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(31)
  LevelPartyLT(33)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(32)
  LevelPartyLT(34)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(33)
  LevelPartyLT(35)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(34)
  LevelPartyLT(36)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(35)
  LevelPartyLT(37)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(36)
  LevelPartyLT(38)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(37)
  LevelPartyLT(39)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(38)
  LevelPartyLT(40)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(39)
  LevelPartyLT(41)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(40)
  LevelPartyLT(42)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(41)
  LevelPartyLT(43)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(42)
  LevelPartyLT(44)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(43)
  LevelPartyLT(45)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(44)
  LevelPartyLT(46)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(45)
  LevelPartyLT(47)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(46)
  LevelPartyLT(48)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(47)
  LevelPartyLT(49)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(48)
  LevelPartyLT(50)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(49)
  LevelPartyLT(51)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(50)
  LevelPartyLT(52)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(51)
  LevelPartyLT(53)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(52)
  LevelPartyLT(54)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(53)
  LevelPartyLT(55)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(54)
  LevelPartyLT(56)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(55)
  LevelPartyLT(57)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(56)
  LevelPartyLT(58)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(57)
  LevelPartyLT(59)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(58)
  LevelPartyLT(60)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(59)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(19)
  LevelPartyLT(21)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(20)
  LevelPartyLT(22)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(21)
  LevelPartyLT(23)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(22)
  LevelPartyLT(24)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(23)
  LevelPartyLT(25)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(24)
  LevelPartyLT(26)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(25)
  LevelPartyLT(27)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(26)
  LevelPartyLT(28)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(27)
  LevelPartyLT(29)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(28)
  LevelPartyLT(30)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(29)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(19)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(14)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(11)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(9)
  Global("SpawnReset10281582","AR7000",0)
  Global("RandomSet10281582_0","AR7000",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    CreateCreature("WOLFDR",[1028.1582],0)  // ~Dread Wolf~
    SetGlobalTimer("220010281582","AR7000",2400)
END

IF
  !Range([PC],35)
  Global("SpawnReset10281582","AR7000",1)
  GlobalTimerExpired("220010281582","AR7000")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",0)
    SetGlobal("RandomBeenSet10281582","AR7000",0)
    SetGlobal("RandomSet10281582_2","AR7000",0)
    SetGlobal("RandomSet10281582_1","AR7000",0)
    SetGlobal("RandomSet10281582_0","AR7000",0)
END

IF
  Range([PC],35)
  Global("SpawnReset10281582","AR7000",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset10281582","AR7000",1)
    CreateCreature("TASLOI",[1028.1582],0)  // ~Tasloi~
    SetGlobalTimer("220010281582","AR7000",2400)
END

