IF
  RandomNum(5,1)
  Global("RandomSet37021965_4","AR3100",0)
  Global("RandomBeenSet37021965","AR3100",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet37021965_4","AR3100",1)
    SetGlobal("RandomBeenSet37021965","AR3100",1)
END

IF
  RandomNum(5,2)
  Global("RandomSet37021965_3","AR3100",0)
  Global("RandomBeenSet37021965","AR3100",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet37021965_3","AR3100",1)
    SetGlobal("RandomBeenSet37021965","AR3100",1)
END

IF
  RandomNum(5,3)
  Global("RandomSet37021965_2","AR3100",0)
  Global("RandomBeenSet37021965","AR3100",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet37021965_2","AR3100",1)
    SetGlobal("RandomBeenSet37021965","AR3100",1)
END

IF
  RandomNum(5,4)
  Global("RandomSet37021965_1","AR3100",0)
  Global("RandomBeenSet37021965","AR3100",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet37021965_1","AR3100",1)
    SetGlobal("RandomBeenSet37021965","AR3100",1)
END

IF
  RandomNum(5,5)
  Global("RandomSet37021965_0","AR3100",0)
  Global("RandomBeenSet37021965","AR3100",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet37021965_0","AR3100",1)
    SetGlobal("RandomBeenSet37021965","AR3100",1)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(19)
  LevelPartyLT(21)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(20)
  LevelPartyLT(22)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(21)
  LevelPartyLT(23)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(22)
  LevelPartyLT(24)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(23)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(11)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_4","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    CreateCreature("GNOLL_D",[3702.1965],0)  // ~Gnoll Slasher~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(19)
  LevelPartyLT(21)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(20)
  LevelPartyLT(22)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(21)
  LevelPartyLT(23)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(22)
  LevelPartyLT(24)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(23)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(11)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_3","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL_B",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(19)
  LevelPartyLT(21)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(20)
  LevelPartyLT(22)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(21)
  LevelPartyLT(23)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(22)
  LevelPartyLT(24)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(23)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(11)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_2","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    CreateCreature("GNOLL_A",[3702.1965],0)  // ~Gnoll Elite~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(19)
  LevelPartyLT(21)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(20)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(10)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_1","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(19)
  LevelPartyLT(21)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(20)
  LevelPartyLT(22)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(21)
  LevelPartyLT(23)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(22)
  LevelPartyLT(24)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(23)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(11)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(7)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(3)
  Global("SpawnReset37021965","AR3100",0)
  Global("RandomSet37021965_0","AR3100",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    CreateCreature("GNOLL",[3702.1965],0)  // ~Gnoll~
    SetGlobalTimer("420037021965","AR3100",2400)
END

IF
  !Range([PC],35)
  Global("SpawnReset37021965","AR3100",1)
  GlobalTimerExpired("420037021965","AR3100")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",0)
    SetGlobal("RandomBeenSet37021965","AR3100",0)
    SetGlobal("RandomSet37021965_4","AR3100",0)
    SetGlobal("RandomSet37021965_3","AR3100",0)
    SetGlobal("RandomSet37021965_2","AR3100",0)
    SetGlobal("RandomSet37021965_1","AR3100",0)
    SetGlobal("RandomSet37021965_0","AR3100",0)
END

IF
  Range([PC],35)
  Global("SpawnReset37021965","AR3100",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset37021965","AR3100",1)
    CreateCreature("BGWOLF",[3702.1965],0)  // ~Wolf~
    SetGlobalTimer("420037021965","AR3100",2400)
END

