IF
  RandomNum(6,1)
  Global("RandomSet47762809_5","AR4300",0)
  Global("RandomBeenSet47762809","AR4300",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet47762809_5","AR4300",1)
    SetGlobal("RandomBeenSet47762809","AR4300",1)
END

IF
  RandomNum(6,2)
  Global("RandomSet47762809_4","AR4300",0)
  Global("RandomBeenSet47762809","AR4300",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet47762809_4","AR4300",1)
    SetGlobal("RandomBeenSet47762809","AR4300",1)
END

IF
  RandomNum(6,3)
  Global("RandomSet47762809_3","AR4300",0)
  Global("RandomBeenSet47762809","AR4300",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet47762809_3","AR4300",1)
    SetGlobal("RandomBeenSet47762809","AR4300",1)
END

IF
  RandomNum(6,4)
  Global("RandomSet47762809_2","AR4300",0)
  Global("RandomBeenSet47762809","AR4300",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet47762809_2","AR4300",1)
    SetGlobal("RandomBeenSet47762809","AR4300",1)
END

IF
  RandomNum(6,5)
  Global("RandomSet47762809_1","AR4300",0)
  Global("RandomBeenSet47762809","AR4300",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet47762809_1","AR4300",1)
    SetGlobal("RandomBeenSet47762809","AR4300",1)
END

IF
  RandomNum(6,6)
  Global("RandomSet47762809_0","AR4300",0)
  Global("RandomBeenSet47762809","AR4300",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet47762809_0","AR4300",1)
    SetGlobal("RandomBeenSet47762809","AR4300",1)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(14)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_5","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(14)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_4","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(19)
  LevelPartyLT(21)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(20)
  LevelPartyLT(22)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(21)
  LevelPartyLT(23)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(22)
  LevelPartyLT(24)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(23)
  LevelPartyLT(25)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(24)
  LevelPartyLT(26)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(25)
  LevelPartyLT(27)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(26)
  LevelPartyLT(28)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(27)
  LevelPartyLT(29)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(28)
  LevelPartyLT(30)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(29)
  LevelPartyLT(31)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(30)
  LevelPartyLT(32)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(31)
  LevelPartyLT(33)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(32)
  LevelPartyLT(34)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(33)
  LevelPartyLT(35)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(34)
  LevelPartyLT(36)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(35)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(17)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(11)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(8)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_3","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    CreateCreature("KOBCOMM",[4776.2809],0)  // ~Kobold Commando~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(14)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_2","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    CreateCreature("SKELET_C",[4776.2809],0)  // ~Skeleton~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(11)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(1)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(11)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(5)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(1)
  Global("SpawnReset47762809","AR4300",0)
  Global("RandomSet47762809_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    CreateCreature("XVART_C",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

IF
  !Range([PC],35)
  Global("SpawnReset47762809","AR4300",1)
  GlobalTimerExpired("530047762809","AR4300")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",0)
    SetGlobal("RandomBeenSet47762809","AR4300",0)
    SetGlobal("RandomSet47762809_5","AR4300",0)
    SetGlobal("RandomSet47762809_4","AR4300",0)
    SetGlobal("RandomSet47762809_3","AR4300",0)
    SetGlobal("RandomSet47762809_2","AR4300",0)
    SetGlobal("RandomSet47762809_1","AR4300",0)
    SetGlobal("RandomSet47762809_0","AR4300",0)
END

IF
  Range([PC],35)
  Global("SpawnReset47762809","AR4300",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset47762809","AR4300",1)
    CreateCreature("XVART_B",[4776.2809],0)  // ~Xvart~
    SetGlobalTimer("530047762809","AR4300",2400)
END

