IF
  RandomNum(2,1)
  Global("RandomSet23403320_1","AR4300",0)
  Global("RandomBeenSet23403320","AR4300",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet23403320_1","AR4300",1)
    SetGlobal("RandomBeenSet23403320","AR4300",1)
END

IF
  RandomNum(2,2)
  Global("RandomSet23403320_0","AR4300",0)
  Global("RandomBeenSet23403320","AR4300",0)
THEN
  RESPONSE #100
    SetGlobal("RandomSet23403320_0","AR4300",1)
    SetGlobal("RandomBeenSet23403320","AR4300",1)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(19)
  LevelPartyLT(21)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(20)
  LevelPartyLT(22)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(21)
  LevelPartyLT(23)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(22)
  LevelPartyLT(24)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(23)
  LevelPartyLT(25)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(24)
  LevelPartyLT(26)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(25)
  LevelPartyLT(27)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(26)
  LevelPartyLT(28)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(27)
  LevelPartyLT(29)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(28)
  LevelPartyLT(30)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(29)
  LevelPartyLT(31)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(30)
  LevelPartyLT(32)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(31)
  LevelPartyLT(33)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(32)
  LevelPartyLT(34)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(33)
  LevelPartyLT(35)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(34)
  LevelPartyLT(36)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(35)
  LevelPartyLT(37)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(36)
  LevelPartyLT(38)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(37)
  LevelPartyLT(39)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(38)
  LevelPartyLT(40)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(39)
  LevelPartyLT(41)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(40)
  LevelPartyLT(42)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(41)
  LevelPartyLT(43)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(42)
  LevelPartyLT(44)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(43)
  LevelPartyLT(45)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(44)
  LevelPartyLT(46)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(45)
  LevelPartyLT(47)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(46)
  LevelPartyLT(48)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(47)
  LevelPartyLT(49)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(48)
  LevelPartyLT(50)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(49)
  LevelPartyLT(51)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(50)
  LevelPartyLT(52)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(51)
  LevelPartyLT(53)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(52)
  LevelPartyLT(54)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(53)
  LevelPartyLT(55)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(54)
  LevelPartyLT(56)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(55)
  LevelPartyLT(57)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(56)
  LevelPartyLT(58)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(57)
  LevelPartyLT(59)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(58)
  LevelPartyLT(60)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(59)
  LevelPartyLT(61)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(60)
  LevelPartyLT(62)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(61)
  LevelPartyLT(63)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(62)
  LevelPartyLT(64)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(63)
  LevelPartyLT(65)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(64)
  LevelPartyLT(66)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(65)
  LevelPartyLT(67)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(66)
  LevelPartyLT(68)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(67)
  LevelPartyLT(69)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(68)
  LevelPartyLT(70)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(69)
  LevelPartyLT(71)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(70)
  LevelPartyLT(72)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(71)
  LevelPartyLT(73)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(72)
  LevelPartyLT(74)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(73)
  LevelPartyLT(75)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(74)
  LevelPartyLT(76)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(75)
  LevelPartyLT(77)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(76)
  LevelPartyLT(78)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(77)
  LevelPartyLT(79)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(78)
  LevelPartyLT(80)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(79)
  LevelPartyLT(81)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(80)
  LevelPartyLT(82)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(81)
  LevelPartyLT(83)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(82)
  LevelPartyLT(84)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(83)
  LevelPartyLT(85)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(84)
  LevelPartyLT(86)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(85)
  LevelPartyLT(87)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(86)
  LevelPartyLT(88)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(87)
  LevelPartyLT(89)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(88)
  LevelPartyLT(90)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(89)
  LevelPartyLT(91)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(90)
  LevelPartyLT(92)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(91)
  LevelPartyLT(93)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(92)
  LevelPartyLT(94)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(93)
  LevelPartyLT(95)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(94)
  LevelPartyLT(96)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(95)
  LevelPartyLT(97)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(96)
  LevelPartyLT(98)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(97)
  LevelPartyLT(99)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(98)
  LevelPartyLT(100)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(99)
  LevelPartyLT(101)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(100)
  LevelPartyLT(102)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(101)
  LevelPartyLT(103)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(102)
  LevelPartyLT(104)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(103)
  LevelPartyLT(105)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(104)
  LevelPartyLT(106)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(105)
  LevelPartyLT(107)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(106)
  LevelPartyLT(108)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(107)
  LevelPartyLT(109)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(108)
  LevelPartyLT(110)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(109)
  LevelPartyLT(111)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(110)
  LevelPartyLT(112)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(111)
  LevelPartyLT(113)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(112)
  LevelPartyLT(114)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(113)
  LevelPartyLT(115)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(114)
  LevelPartyLT(116)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(115)
  LevelPartyLT(117)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(116)
  LevelPartyLT(118)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(117)
  LevelPartyLT(119)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(118)
  LevelPartyLT(120)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(119)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(19)
  LevelPartyLT(21)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(20)
  LevelPartyLT(22)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(21)
  LevelPartyLT(23)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(22)
  LevelPartyLT(24)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(23)
  LevelPartyLT(25)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(24)
  LevelPartyLT(26)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(25)
  LevelPartyLT(27)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(26)
  LevelPartyLT(28)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(27)
  LevelPartyLT(29)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(28)
  LevelPartyLT(30)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(29)
  LevelPartyLT(31)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(30)
  LevelPartyLT(32)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(31)
  LevelPartyLT(33)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(32)
  LevelPartyLT(34)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(33)
  LevelPartyLT(35)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(34)
  LevelPartyLT(36)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(35)
  LevelPartyLT(37)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(36)
  LevelPartyLT(38)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(37)
  LevelPartyLT(39)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(38)
  LevelPartyLT(40)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(39)
  LevelPartyLT(41)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(40)
  LevelPartyLT(42)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(41)
  LevelPartyLT(43)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(42)
  LevelPartyLT(44)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(43)
  LevelPartyLT(45)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(44)
  LevelPartyLT(46)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(45)
  LevelPartyLT(47)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(46)
  LevelPartyLT(48)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(47)
  LevelPartyLT(49)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(48)
  LevelPartyLT(50)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(49)
  LevelPartyLT(51)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(50)
  LevelPartyLT(52)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(51)
  LevelPartyLT(53)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(52)
  LevelPartyLT(54)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(53)
  LevelPartyLT(55)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(54)
  LevelPartyLT(56)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(55)
  LevelPartyLT(57)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(56)
  LevelPartyLT(58)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(57)
  LevelPartyLT(59)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(58)
  LevelPartyLT(60)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(59)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(19)
  LevelPartyLT(21)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(20)
  LevelPartyLT(22)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(21)
  LevelPartyLT(23)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(22)
  LevelPartyLT(24)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(23)
  LevelPartyLT(25)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(24)
  LevelPartyLT(26)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(25)
  LevelPartyLT(27)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(26)
  LevelPartyLT(28)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(27)
  LevelPartyLT(29)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(28)
  LevelPartyLT(30)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(29)
  LevelPartyLT(31)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(30)
  LevelPartyLT(32)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(31)
  LevelPartyLT(33)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(32)
  LevelPartyLT(34)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(33)
  LevelPartyLT(35)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(34)
  LevelPartyLT(36)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(35)
  LevelPartyLT(37)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(36)
  LevelPartyLT(38)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(37)
  LevelPartyLT(39)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(38)
  LevelPartyLT(40)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(39)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(19)
  LevelPartyLT(21)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(20)
  LevelPartyLT(22)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(21)
  LevelPartyLT(23)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(22)
  LevelPartyLT(24)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(23)
  LevelPartyLT(25)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(24)
  LevelPartyLT(26)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(25)
  LevelPartyLT(27)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(26)
  LevelPartyLT(28)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(27)
  LevelPartyLT(29)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(28)
  LevelPartyLT(30)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(29)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(19)
  LevelPartyLT(21)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(20)
  LevelPartyLT(22)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(21)
  LevelPartyLT(23)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(22)
  LevelPartyLT(24)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(23)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(14)
  LevelPartyLT(16)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(15)
  LevelPartyLT(17)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(16)
  LevelPartyLT(18)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(17)
  LevelPartyLT(19)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(18)
  LevelPartyLT(20)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(19)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_1","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    CreateCreature("BEARCA",[2340.3320],0)  // ~Cave Bear~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(7)
  LevelPartyLT(9)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(8)
  LevelPartyLT(10)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(9)
  LevelPartyLT(11)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(10)
  LevelPartyLT(12)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(11)
  LevelPartyLT(13)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(12)
  LevelPartyLT(14)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(13)
  LevelPartyLT(15)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(1)
  LevelPartyGT(14)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(4)
  LevelPartyLT(6)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(5)
  LevelPartyLT(7)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(6)
  LevelPartyLT(8)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(2)
  LevelPartyGT(7)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(3)
  LevelPartyLT(5)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(3)
  LevelPartyGT(4)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(2)
  LevelPartyLT(4)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(4)
  LevelPartyGT(3)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(5)
  LevelPartyGT(2)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(0)
  LevelPartyLT(2)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(1)
  LevelPartyLT(3)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  Range([PC],35)
  NumInPartyAlive(6)
  LevelPartyGT(2)
  Global("SpawnReset23403320","AR4300",0)
  Global("RandomSet23403320_0","AR4300",1)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

IF
  !Range([PC],35)
  Global("SpawnReset23403320","AR4300",1)
  GlobalTimerExpired("530023403320","AR4300")
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",0)
    SetGlobal("RandomBeenSet23403320","AR4300",0)
    SetGlobal("RandomSet23403320_1","AR4300",0)
    SetGlobal("RandomSet23403320_0","AR4300",0)
END

IF
  Range([PC],35)
  Global("SpawnReset23403320","AR4300",0)
THEN
  RESPONSE #100
    SetGlobal("SpawnReset23403320","AR4300",1)
    CreateCreature("SKELET_B",[2340.3320],0)  // ~Skeleton~
    SetGlobalTimer("530023403320","AR4300",2400)
END

